"""Add following table

Revision ID: 61317375e3ad
Revises: 784d312dd371
Create Date: 2020-05-25 14:35:02.609410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61317375e3ad"
down_revision = "784d312dd371"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "following",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("follows_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["follows_id"], ["users.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("following")
    # ### end Alembic commands ###
